import argparse
from collections import deque
from PIL import Image

COLS = 56
ROWS = 28  # each row = 2 pixel-rows via half-block trick -> pixel grid is COLS x (ROWS*2)

BG_THRESHOLD = 60  # euclidean-ish distance from white to treat as background
ALPHA_CUTOFF = 128


def near_white(rgb):
    r, g, b = rgb
    return (255 - r) + (255 - g) + (255 - b) < BG_THRESHOLD


def flood_fill_background(img):
    """Mark near-white pixels reachable from the image border as background.
    Keeps interior near-white regions (like the unicorn's body) intact, since
    they're enclosed by non-white outline pixels and never connect to the edge.
    """
    w, h = img.size
    px = img.load()
    visited = [[False] * w for _ in range(h)]
    q = deque()

    for x in range(w):
        for y in (0, h - 1):
            if not visited[y][x] and near_white(px[x, y]):
                visited[y][x] = True
                q.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if not visited[y][x] and near_white(px[x, y]):
                visited[y][x] = True
                q.append((x, y))

    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not visited[ny][nx] and near_white(px[nx, ny]):
                visited[ny][nx] = True
                q.append((nx, ny))

    return visited  # visited[y][x] == True means "background"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("src", help="source image path")
    parser.add_argument("out", help="output .lua path")
    parser.add_argument("--cols", type=int, default=COLS)
    parser.add_argument("--rows", type=int, default=ROWS)
    args = parser.parse_args()

    img = Image.open(args.src).convert("RGB")
    bg_mask = flood_fill_background(img)
    w, h = img.size
    rgba = Image.new("RGBA", (w, h))
    src_px = img.load()
    dst_px = rgba.load()
    for y in range(h):
        for x in range(w):
            r, g, b = src_px[x, y]
            dst_px[x, y] = (r, g, b, 0 if bg_mask[y][x] else 255)

    small = rgba.resize((args.cols, args.rows * 2), Image.LANCZOS)
    px = small.load()

    def get(x, y):
        r, g, b, a = px[x, y]
        return None if a < ALPHA_CUTOFF else (r, g, b)

    rows_out = []
    hl_set = {}
    hl_order = []

    def hex_or_none(c):
        return None if c is None else "#%02x%02x%02x" % c

    def group_name(fg, bg):
        key = (fg, bg)
        if key in hl_set:
            return hl_set[key]
        name = "SnacksDashboardUnicorn%d" % (len(hl_order) + 1)
        hl_set[key] = name
        hl_order.append((name, fg, bg))
        return name

    total_chunks = 0
    for r in range(args.rows):
        y_top = r * 2
        y_bot = r * 2 + 1
        cells = []
        for c in range(args.cols):
            top = get(c, y_top)
            bot = get(c, y_bot)
            if top is None and bot is None:
                cells.append((" ", None, None))
            elif top is not None and bot is not None:
                cells.append(("▀", hex_or_none(top), hex_or_none(bot)))
            elif top is not None:
                cells.append(("▀", hex_or_none(top), None))
            else:
                cells.append(("▄", hex_or_none(bot), None))

        chunks = []
        i = 0
        while i < len(cells):
            ch, fg, bg = cells[i]
            j = i
            while j < len(cells) and cells[j] == (ch, fg, bg):
                j += 1
            run_len = j - i
            text = ch * run_len
            if fg is None and bg is None:
                chunks.append((text, None))
            else:
                gname = group_name(fg, bg)
                chunks.append((text, gname))
            i = j
        total_chunks += len(chunks)
        rows_out.append(chunks)

    lua_lines = []
    lua_lines.append("-- Generated by gen_unicorn_art.py from the Obsidian ricing note's unicorn image.")
    lua_lines.append("-- Do not hand-edit; regenerate instead if the source image or dimensions change.")
    lua_lines.append("local M = {}")
    lua_lines.append("")
    lua_lines.append("M.highlights = {")
    for name, fg, bg in hl_order:
        parts = []
        if fg:
            parts.append('fg = "%s"' % fg)
        if bg:
            parts.append('bg = "%s"' % bg)
        lua_lines.append('  { name = "%s", %s },' % (name, ", ".join(parts)))
    lua_lines.append("}")
    lua_lines.append("")
    lua_lines.append("M.rows = {")
    for chunks in rows_out:
        parts = []
        for text, hl in chunks:
            esc = text.replace("\\", "\\\\").replace('"', '\\"')
            if hl:
                parts.append('{ "%s", hl = "%s" }' % (esc, hl))
            else:
                parts.append('{ "%s" }' % esc)
        lua_lines.append("  { " + ", ".join(parts) + " },")
    lua_lines.append("}")
    lua_lines.append("")
    lua_lines.append("return M")

    with open(args.out, "w") as f:
        f.write("\n".join(lua_lines) + "\n")

    print("cols=%d rows=%d unique_colors=%d total_chunks=%d" % (args.cols, args.rows, len(hl_order), total_chunks))
    print("written to", args.out)


if __name__ == "__main__":
    main()
